### ISSUE TITLE
Error Cannot find module 'ngx-viewer' or its corresponding type declarations 

### ISSUE THREAD

**Issue by jlmonteagudo** [winteragency/ngx-viewer#12]
With version 1.0.5 it was working fine, but the library has been updated to version 1.0.6 and I'm getting the following error:

Cannot find module 'ngx-viewer' or its corresponding type declarations

**Comment by birdman1811** [comment]
Same issue here.

**Comment by ps93** [comment]
Same issue

**Comment by AtoianAvetik** [comment]
Same issue

**Comment by rlunden** [comment]
Fixed by v1.0.8.
