### ISSUE TITLE
How to open image with doubleclick?

### ISSUE THREAD

**Issue by nikitalpopov** [winteragency/ngx-viewer#2]
How can I use doubleclick to open viewer, not single click?

**Comment by marcusforsberg** [comment]
Hi @nikitalpopov,

This module simply wraps the Viewer.js library, so any functionality such as custom even bindings would need to be added as options to the original library, which would then make them available for use through this module as well. You'll probably be better off opening an issue there: https://github.com/fengyuanchen/viewerjs 🙂
