### ISSUE TITLE
Load Thumb and Original seprate

### ISSUE THREAD

**Issue by ikishanoza** [winteragency/ngx-viewer#3]
Is there is any way we can load thumb and original image separate ? like display the thumb image and in viewer display the original ?

**Comment by marcusforsberg** [comment]
This module really just wraps the original Viewerjs library, so anything you can do with that, you should be able to do here as well. I'm guessing the `url` option might be what you're looking for: https://github.com/fengyuanchen/viewerjs/blob/master/README.md#options 🙂
