### ISSUE TITLE
Expose viewer instance

### ISSUE THREAD

**Issue by marcelgood** [winteragency/ngx-viewer#4]
I'm trying to figure out how to call methods such as `view` etc. on the viewer instance, but the viewer instance is private to the directive. Why is it not exposed, or why does the directive not expose similar methods that we can call and proxy them to the viewer instance? What's the recommended way to get a hold of the viewer instance, so I can call methods on it?

**Comment by marcusforsberg** [comment]
Why? We didn't have a need for it when we built this quick directive and haven't since for our use case. :) There's no reason it couldn't be public or have a getViewer() method; feel free to open a PR!

**Comment by marcelgood** [comment]
I've created a PR. The reason is that the viewer has many useful methods, such as `view` to open an image at a specific index or `update` to refresh the viewer after dynamically adding more images.

https://github.com/winteragency/ngx-viewer/pull/5
